language: python
python: "2.7"
sudo: required
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  matrix:
    - SOLR_VERSION=4.10.4
    - SOLR_VERSION=5.2.1
    - SOLR_VERSION=6.6.5
    - SOLR_VERSION=7.2.1
    - SOLR_VERSION=7.3.0
    - SOLR_VERSION=7.4.0
    - SOLR_VERSION=7.5.0
    - SOLR_VERSION=7.6.0
    - SOLR_VERSION=7.7.1
    - SOLR_VERSION=8.2.0
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install -r requirements.txt
install:
  - sed -ie "s#7.4.0#$SOLR_VERSION#" buildout.cfg
  - sed -ie "s#solr-7.4.0#solr-$SOLR_VERSION#" buildout.cfg
  - bin/buildout
script:
  - bin/code-analysis
  - bin/test
