language: python
python: "2.7"
sudo: required
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  matrix:
    - SOLR_VERSION=7.2.1
    - SOLR_VERSION=7.3.0
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install -r requirements.txt
install:
  - sed -ie "s#7.3.0#$SOLR_VERSION#" buildout.cfg
  - bin/buildout
script:
  - bin/test
